### ISSUE TITLE
spiff++ fails to generate the diego manifest (where spiff works fine)

### ISSUE THREAD

**Issue by michaelgrifalconi** [mandelsoft/spiff-fork#4]
How to reproduce:

Follow the steps in https://github.com/cloudfoundry/diego-release/tree/v0.1489.0/examples/bosh-lite

1 - clone on ~/workspace/github.com/cloudfoundry/cf-release the cf-release v247
2 - clone on ~/workspace/github.com/cloudfoundry/diego-release the diego-release v0.1489.0
3 - ```cd ~/workspace/github.com/cloudfounry/cf-release ```
4 - ```./scripts/generate-bosh-lite-dev-manifest```
5 - ``` cd ~/workspace/github.com/cloudfounry/diego-release```
6 - ```USE_SQL='postgres' ./scripts/generate-bosh-lite-manifests```

Step #6 will fail with the following error:
https://gist.github.com/tyyko/4120b2d08175657a31cd2af46b9dccff

while spiff 1.7.0 works just fine

**Comment by michaelgrifalconi** [comment]
Update: also spiff have some errors, randomly. Sometime it works sometime it doesn't

**Comment by mandelsoft** [comment]
Hi Michael,

is this on MAC?  It looks like the Sierra Problem.
With lastest Go 1.7 it should be fixed.

Once Stephan is back this week, we will reorganize the spiff project to use GO 1.7.

Regards
Uwe

**Comment by michaelgrifalconi** [comment]
yes it is, I agree it looks more a go issue even is quite strange that only sometimes it fails.

looking forward for the binary compiled with 1.7, thanks!

**Comment by mandelsoft** [comment]
I've released a new version with go 1.7. This should solve the problem on Sierra.
Regards
Uwe
